import type { Activity, Question } from './content';

export type BankArea = 'letters' | 'sounds' | 'words' | 'sentences' | 'reading' | 'logic';
export type BankFormat = 'choice' | 'completion' | 'intruder' | 'true-false' | 'order' | 'multi' | 'match' | 'reading' | 'logic';
export type BankLevel = 'beginner' | 'developing' | 'challenge';
export type BankActivity = Activity & {
  area: BankArea;
  format: BankFormat;
  level: BankLevel;
  objective: string;
  teacherTip: string;
};

type DraftQuestion = Omit<Question, 'id'>;
type Extras = Pick<Question, 'stimulus' | 'visual' | 'audioText'>;

function choice(prompt: string, options: string[], answer: string, explanation: string, extra: Extras = {}): DraftQuestion {
  return { type: 'choice', prompt, options, answer, explanation, ...extra };
}
function order(prompt: string, options: string[], answer: string[], explanation: string, extra: Extras = {}): DraftQuestion {
  return { type: 'order', prompt, options, answer, explanation, ...extra };
}
function multi(prompt: string, options: string[], answer: string[], explanation: string, extra: Extras = {}): DraftQuestion {
  return { type: 'multi', prompt, options, answer, explanation, ...extra };
}
function match(prompt: string, options: string[], matches: string[], answer: string[], explanation: string, extra: Extras = {}): DraftQuestion {
  return { type: 'match', prompt, options, matches, answer, explanation, ...extra };
}

const worldByArea: Record<BankArea, number> = { letters: 1, sounds: 2, words: 3, sentences: 4, reading: 5, logic: 3 };
function activity(area: BankArea, slug: string, title: string, description: string, format: BankFormat, level: BankLevel, skill: string, objective: string, teacherTip: string, questions: DraftQuestion[], durationMinutes = 5): BankActivity {
  const id = 'bank-' + slug;
  const worldId = worldByArea[area];
  return { id, worldId, area, title, description, format, level, skill, objective, teacherTip, type: questions[0].type, durationMinutes, xp: 40,
    questions: questions.map((question, index) => ({ ...question, id: id + '-q' + (index + 1), worldId })) };
}

/** Independent teacher-bank practice; these activities do not add steps to the official trail. */
export const supplementalActivities: BankActivity[] = [
  activity('letters', 'letras-lupa', 'Letras sob a lupa', 'Investigue a posição e a repetição das letras em palavras do cotidiano.', 'choice', 'beginner', 'Identificação de letras em palavras', 'Localizar letras iniciais, finais e repetidas sem confundir letra com sílaba.', 'Peça à criança que aponte cada letra antes de responder. Nomeie as letras sem exigir leitura fluente.', [
    choice('Qual é a última letra de PIPOCA?', ['P', 'I', 'A', 'C'], 'A', 'PIPOCA termina com A. Acompanhe as letras da esquerda para a direita.', { stimulus: 'PIPOCA', visual: '🍿' }),
    choice('Qual é a terceira letra de TATU?', ['U', 'A', 'T', 'O'], 'T', 'Conte da esquerda para a direita: T, A, T, U. A terceira letra é T.', { stimulus: 'T A T U' }),
    choice('Qual letra aparece três vezes em BATATA?', ['B', 'T', 'A', 'E'], 'A', 'BATATA tem três A: B-A-T-A-T-A. Tem dois T e um B.', { stimulus: 'BATATA', visual: '🥔' }),
    choice('Qual palavra começa com J?', ['GIRAFA', 'JABUTI', 'SAPO', 'COELHO'], 'JABUTI', 'JABUTI começa com a letra J. GIRAFA começa com G, mesmo com um som inicial parecido.', { visual: '🔎' }),
  ]),
  activity('letters', 'letras-lacunas', 'Correio das letras perdidas', 'Entregue a letra que falta em cada palavra usando a pista.', 'completion', 'beginner', 'Correspondência entre letras e palavras', 'Completar a grafia de palavras familiares apoiando-se na pista de significado.', 'Leia a pista e a palavra completa em voz alta quando necessário. Depois, compare a escrita com a resposta.', [
    choice('Qual letra completa o nome do inseto que produz mel?', ['B', 'P', 'M', 'T'], 'B', 'A-B-E-L-H-A forma ABELHA. A letra que faltava era B.', { stimulus: 'A_ELHA', visual: '🐝' }),
    choice('Qual letra completa o nome do astro que vemos durante o dia?', ['A', 'O', 'E', 'I'], 'O', 'S-O-L forma SOL. A vogal do meio é O.', { stimulus: 'S_L', visual: '☀️' }),
    choice('Qual letra completa o nome do brinquedo que voa preso a uma linha?', ['B', 'D', 'P', 'M'], 'P', 'P-I-P-A forma PIPA. Faltava a primeira letra P.', { stimulus: '_IPA', visual: '🪁' }),
    choice('Qual letra completa o nome da fruta da pista?', ['V', 'F', 'L', 'T'], 'V', 'U-V-A forma UVA. A consoante entre as vogais é V.', { stimulus: 'U_A', visual: '🍇' }),
  ]),
  activity('letters', 'letras-colecoes', 'Coleções do alfabeto', 'Escolha todas as letras ou palavras que seguem a regra da coleção.', 'multi', 'developing', 'Classificação de letras e palavras', 'Selecionar mais de um exemplo de uma propriedade e excluir os que não a apresentam.', 'Lembre que pode haver várias respostas. Convide a criança a justificar também uma opção que deixou de fora.', [
    multi('Marque todas as vogais desta coleção.', ['E', 'B', 'U', 'M'], ['E', 'U'], 'E e U são vogais. B e M são consoantes.', { visual: '🧺' }),
    multi('Marque todas as palavras que começam com C.', ['CASA', 'SAPO', 'COPO', 'FITA'], ['CASA', 'COPO'], 'CASA e COPO começam com C. SAPO começa com S e FITA com F.'),
    multi('Marque todas as letras escritas em minúscula.', ['a', 'B', 'm', 'R'], ['a', 'm'], 'a e m são minúsculas. Suas formas maiúsculas são A e M.'),
    multi('Marque todas as palavras que terminam com A.', ['LUA', 'SOL', 'MALA', 'MAR'], ['LUA', 'MALA'], 'A última letra de LUA e de MALA é A. SOL termina com L e MAR com R.'),
  ], 6),
  activity('letters', 'letras-pares', 'Pares da árvore das letras', 'Ligue letras, formas de escrita e palavras que começam com elas.', 'match', 'developing', 'Associação de letras maiúsculas e minúsculas', 'Relacionar representações da mesma letra e reconhecer iniciais de palavras.', 'Faça um par de exemplo com letras móveis. Use o nome da letra, diferenciando-o do nome do desenho.', [
    match('Ligue cada letra maiúscula à sua forma minúscula.', ['A', 'M', 'F'], ['f', 'a', 'm'], ['a', 'm', 'f'], 'A combina com a, M com m e F com f. A forma muda, mas a letra continua a mesma.'),
    match('Ligue cada letra minúscula à sua forma maiúscula.', ['b', 'd', 'p'], ['P', 'B', 'D'], ['B', 'D', 'P'], 'b corresponde a B, d a D e p a P. Observe a posição da haste em cada minúscula.'),
    match('Ligue cada letra à palavra que começa com ela.', ['L', 'V', 'N'], ['NAVIO', 'LAGO', 'VELA'], ['LAGO', 'VELA', 'NAVIO'], 'LAGO começa com L, VELA com V e NAVIO com N.'),
    match('Ligue cada palavra à sua última letra.', ['MAR', 'PAPEL', 'TATU'], ['U', 'R', 'L'], ['R', 'L', 'U'], 'MAR termina com R, PAPEL com L e TATU com U. Para conferir, olhe a ponta direita da palavra.'),
  ], 6),
  activity('letters', 'letras-intrusa', 'A letra fora do clube', 'Descubra qual opção não segue a regra do grupo.', 'intruder', 'developing', 'Comparação de propriedades da escrita', 'Reconhecer diferenças entre vogais, consoantes, iniciais e formas de escrita.', 'Leia a regra de cada grupo antes das opções. Pergunte o que as outras três têm em comum.', [
    choice('O clube é das vogais. Qual letra ficou no grupo errado?', ['A', 'E', 'T', 'I'], 'T', 'T é uma consoante. A, E e I são vogais.'),
    choice('O clube é das palavras que começam com B. Qual está no grupo errado?', ['BALA', 'BOTA', 'PATO', 'BULE'], 'PATO', 'PATO começa com P. BALA, BOTA e BULE começam com B.'),
    choice('O clube é das letras maiúsculas. Qual está no grupo errado?', ['L', 'N', 'r', 'S'], 'r', 'r é minúscula. As outras letras estão em maiúscula.'),
    choice('O clube é das palavras com quatro letras. Qual está no grupo errado?', ['MESA', 'FITA', 'JANELA', 'LAGO'], 'JANELA', 'JANELA tem seis letras. MESA, FITA e LAGO têm quatro.', { visual: '🔍' }),
  ]),
  activity('letters', 'letras-sequencias', 'Escada do alfabeto', 'Organize pequenos trechos do alfabeto e palavras pela letra inicial.', 'order', 'challenge', 'Ordenação alfabética inicial', 'Usar a sequência alfabética para ordenar letras e palavras com iniciais diferentes.', 'Deixe um alfabeto visível como apoio. Na última questão, compare somente as letras iniciais.', [
    order('Organize este começo do alfabeto.', ['C', 'A', 'D', 'B'], ['A', 'B', 'C', 'D'], 'O alfabeto começa com A, B, C, D.'),
    order('Coloque estas letras em ordem alfabética, começando por L.', ['N', 'O', 'L', 'M'], ['L', 'M', 'N', 'O'], 'Neste trecho, a ordem é L, M, N, O.'),
    order('Organize as vogais na ordem em que aparecem no alfabeto.', ['O', 'A', 'U', 'E', 'I'], ['A', 'E', 'I', 'O', 'U'], 'As vogais aparecem nesta ordem: A, E, I, O, U.'),
    order('Organize as palavras em ordem alfabética pela primeira letra.', ['DADO', 'ABELHA', 'CASA', 'BOLA'], ['ABELHA', 'BOLA', 'CASA', 'DADO'], 'As iniciais são A, B, C e D: ABELHA, BOLA, CASA, DADO.', { visual: '🪜' }),
  ], 6),

  activity('sounds', 'sons-orquestra', 'Orquestra dos começos', 'Compare os sons iniciais de palavras familiares.', 'choice', 'beginner', 'Discriminação de sons iniciais', 'Identificar palavras que começam com o mesmo som, com apoio da fala do adulto ou do áudio.', 'Fale as palavras naturalmente e depois destaque o som inicial. Evite acrescentar uma vogal ao som de F ou V.', [
    choice('Qual palavra começa com o mesmo som de VENTO?', ['FOLHA', 'VACA', 'PATO', 'MESA'], 'VACA', 'VENTO e VACA começam com o som de V.', { stimulus: 'VENTO', visual: '🍃' }),
    choice('Qual palavra começa com o mesmo som de NUVEM?', ['DADO', 'LATA', 'NINHO', 'BOLA'], 'NINHO', 'NUVEM e NINHO começam com o som de N.', { stimulus: 'NUVEM', visual: '☁️' }),
    choice('Qual palavra começa com o mesmo som de BICO?', ['PIPA', 'BOTA', 'TATU', 'GATO'], 'BOTA', 'BICO e BOTA começam com o som de B. PIPA começa com outro som.', { stimulus: 'BICO' }),
    choice('Qual palavra começa com o mesmo som de DEDO?', ['TETO', 'DADO', 'SAPO', 'FITA'], 'DADO', 'DEDO e DADO começam com o som de D.', { stimulus: 'DEDO' }),
  ]),
  activity('sounds', 'sons-encontros', 'Encontros sonoros', 'Forme pares de rimas, sílabas iniciais e quantidades de sílabas.', 'match', 'developing', 'Associação por semelhança sonora', 'Relacionar palavras usando diferentes critérios de consciência fonológica.', 'Diga qual critério está valendo a cada questão. A semelhança sonora pode estar no começo ou no final.', [
    match('Ligue cada palavra à que rima com ela.', ['GATO', 'JANELA', 'BOTÃO'], ['LIMÃO', 'PATO', 'PANELA'], ['PATO', 'PANELA', 'LIMÃO'], 'GATO rima com PATO; JANELA com PANELA; BOTÃO com LIMÃO.'),
    match('Ligue as palavras que começam com a mesma sílaba.', ['BALA', 'FADA', 'PIPA'], ['PIRATA', 'BAGAGEM', 'FARINHA'], ['BAGAGEM', 'FARINHA', 'PIRATA'], 'BALA e BAGAGEM começam com BA; FADA e FARINHA com FA; PIPA e PIRATA com PI.'),
    match('Ligue cada palavra à quantidade de sílabas.', ['PÉ', 'FOCA', 'PETECA'], ['3 sílabas', '1 sílaba', '2 sílabas'], ['1 sílaba', '2 sílabas', '3 sílabas'], 'PÉ tem uma sílaba; FO-CA tem duas; PE-TE-CA tem três.'),
    match('Ligue cada palavra à sua primeira sílaba.', ['NUVEM', 'BONECA', 'CAVALO'], ['CA', 'NU', 'BO'], ['NU', 'BO', 'CA'], 'NU-VEM começa com NU; BO-NE-CA com BO; CA-VA-LO com CA.'),
  ], 6),
  activity('sounds', 'sons-muitas-pistas', 'Mais de uma pista sonora', 'Encontre todas as palavras que obedecem ao desafio dos sons.', 'multi', 'developing', 'Seleção por rima e estrutura silábica', 'Comparar grupos de palavras e selecionar todos os exemplos de uma regra sonora.', 'Peça que a criança fale todas as opções antes de marcar. Nas contagens, pode bater uma palma por sílaba.', [
    multi('Marque todas as palavras que rimam com PÃO.', ['MÃO', 'PÉ', 'CHÃO', 'SOL'], ['MÃO', 'CHÃO'], 'MÃO e CHÃO rimam com PÃO: as três terminam com o som ÃO.', { stimulus: 'PÃO', visual: '🍞' }),
    multi('Marque todas as palavras que começam com a sílaba MA.', ['MALA', 'MESA', 'MAPA', 'MICO'], ['MALA', 'MAPA'], 'MA-LA e MA-PA começam com MA. MESA começa com ME e MICO com MI.'),
    multi('Marque todas as palavras com duas sílabas.', ['VACA', 'FOGO', 'MACACO', 'MAR'], ['VACA', 'FOGO'], 'VA-CA e FO-GO têm duas sílabas. MA-CA-CO tem três e MAR tem uma.'),
    multi('Marque todas as palavras que terminam com a sílaba TA.', ['LATA', 'BOTA', 'BOLA', 'COPO'], ['LATA', 'BOTA'], 'LA-TA e BO-TA terminam com TA. BOLA termina com LA e COPO com PO.'),
  ], 6),
  activity('sounds', 'sons-desafinou', 'Quem saiu do ritmo?', 'Ache a palavra que não combina com a regra sonora.', 'intruder', 'developing', 'Distinção de padrões sonoros', 'Excluir uma palavra de um grupo de rimas, sons iniciais ou quantidades de sílabas.', 'Retome a regra se a criança escolher pelo significado. Neste jogo, o que conta é a forma como as palavras soam.', [
    choice('Qual palavra NÃO rima com as outras?', ['BOLINHA', 'GALINHA', 'CARRINHO', 'FARINHA'], 'CARRINHO', 'BOLINHA, GALINHA e FARINHA terminam com o som INHA. CARRINHO termina com INHO.'),
    choice('Qual palavra NÃO começa com o som de F?', ['FOGO', 'VACA', 'FACA', 'FOLHA'], 'VACA', 'VACA começa com V. FOGO, FACA e FOLHA começam com F.'),
    choice('Qual palavra NÃO tem três sílabas?', ['PETECA', 'CAVALO', 'GATO', 'TOMATE'], 'GATO', 'GA-TO tem duas sílabas. PE-TE-CA, CA-VA-LO e TO-MA-TE têm três.'),
    choice('Qual palavra NÃO começa com a sílaba PA?', ['PANELA', 'PATO', 'PIPA', 'PAREDE'], 'PIPA', 'PIPA começa com PI. PANELA, PATO e PAREDE começam com PA.'),
  ]),
  activity('sounds', 'sons-transformacoes', 'Oficina das transformações sonoras', 'Retire ou troque sílabas para descobrir novas palavras.', 'completion', 'challenge', 'Manipulação oral de sílabas', 'Identificar resultados de retirada e substituição de sílabas em palavras simples.', 'Diga a palavra inteira e o pedaço que será retirado ou trocado. Use fichas para representar as sílabas.', [
    choice('Tire a sílaba SA do começo de SAPATO. Que palavra sobra?', ['PATO', 'SAPO', 'SACO', 'TAPA'], 'PATO', 'SA-PA-TO sem a primeira sílaba SA fica PA-TO.', { stimulus: 'SA · PA · TO' }),
    choice('Tire a sílaba CO do começo de COCADA. O que sobra?', ['COCA', 'CADA', 'DADO', 'CABO'], 'CADA', 'CO-CA-DA sem CO fica CA-DA.', { stimulus: 'CO · CA · DA' }),
    choice('Troque BO por MA em BO-LA. Que palavra aparece?', ['MALA', 'MOLA', 'MAPA', 'BALA'], 'MALA', 'Ao trocar BO por MA, BO-LA vira MA-LA.', { stimulus: 'BO · LA → MA · __' }),
    choice('Troque TO por NELA em PA-TO. Que palavra aparece?', ['PANELA', 'JANELA', 'PAREDE', 'PETECA'], 'PANELA', 'Mantemos PA e colocamos NELA no lugar de TO: PA-NE-LA.', { stimulus: 'PA · TO' }),
  ], 6),
  activity('sounds', 'sons-conferir', 'Verdadeiro ou falso: ouça de novo', 'Confira descobertas sobre rimas e sílabas.', 'true-false', 'challenge', 'Verificação de relações sonoras', 'Julgar afirmações sobre segmentação e semelhança sonora e explicar as decisões.', 'Peça que a criança corrija as afirmações falsas oralmente. O objetivo é explicar o som, não decorar a resposta.', [
    choice('É verdade que MALA e SALA rimam?', ['Verdadeiro', 'Falso'], 'Verdadeiro', 'MALA e SALA rimam porque o final ALA soa igual.', { stimulus: 'MALA · SALA' }),
    choice('É verdade que ABACATE tem três sílabas?', ['Verdadeiro', 'Falso'], 'Falso', 'A-BA-CA-TE tem quatro sílabas, não três.', { stimulus: 'ABACATE', visual: '🥑' }),
    choice('É verdade que BOLA e BOTA começam com a mesma sílaba?', ['Verdadeiro', 'Falso'], 'Verdadeiro', 'BO-LA e BO-TA começam com a sílaba BO.', { stimulus: 'BOLA · BOTA' }),
    choice('É verdade que FLOR e FOLHA rimam?', ['Verdadeiro', 'Falso'], 'Falso', 'FLOR e FOLHA têm finais sonoros diferentes. FLOR rima com AMOR.', { stimulus: 'FLOR · FOLHA' }),
  ], 6),

  activity('words', 'palavras-canteiro', 'Canteiro das sílabas', 'Complete palavras de plantas, objetos e animais com a sílaba certa.', 'completion', 'developing', 'Completação de palavras por sílabas', 'Usar pistas de significado para escolher a sílaba que completa a palavra.', 'Leia a pista sem dizer a resposta imediatamente. Depois da escolha, convide a criança a reler a palavra formada.', [
    choice('Complete o nome da flor que acompanha a luz do sol.', ['RAS', 'PAS', 'MAS', 'TAS'], 'RAS', 'GI-RAS-SOL forma GIRASSOL. O pedaço que faltava era RAS.', { stimulus: 'GI · __ · SOL', visual: '🌻' }),
    choice('Complete o nome do objeto usado para apagar o lápis.', ['RA', 'LA', 'MA', 'TA'], 'RA', 'BOR-RA-CHA forma BORRACHA.', { stimulus: 'BOR · __ · CHA' }),
    choice('Complete o nome do animal que anda devagar e carrega uma concha.', ['RA', 'NE', 'VA', 'BO'], 'RA', 'CA-RA-COL forma CARACOL.', { stimulus: 'CA · __ · COL', visual: '🐌' }),
    choice('Complete o nome do objeto que usamos para pentear o cabelo.', ['TE', 'TO', 'TA', 'TI'], 'TE', 'PEN-TE forma PENTE.', { stimulus: 'PEN · __' }),
  ]),
  activity('words', 'palavras-estaleiro', 'Estaleiro de palavras', 'Encaixe sílabas na ordem certa para construir quatro palavras.', 'order', 'developing', 'Síntese e ordenação silábica', 'Ordenar sílabas diferentes para reconstruir palavras com três ou quatro sílabas.', 'Após montar, peça uma leitura completa sem pausas entre as sílabas. Use o desenho como pista de significado.', [
    order('Monte a palavra TUCANO.', ['NO', 'TU', 'CA'], ['TU', 'CA', 'NO'], 'TU + CA + NO forma TUCANO.', { stimulus: 'TUCANO', visual: '🐦' }),
    order('Monte a palavra ABACATE.', ['TE', 'BA', 'A', 'CA'], ['A', 'BA', 'CA', 'TE'], 'A + BA + CA + TE forma ABACATE.', { stimulus: 'ABACATE', visual: '🥑' }),
    order('Monte a palavra TELEFONE.', ['FO', 'NE', 'TE', 'LE'], ['TE', 'LE', 'FO', 'NE'], 'TE + LE + FO + NE forma TELEFONE.', { stimulus: 'TELEFONE', visual: '☎️' }),
    order('Monte a palavra CAMISETA.', ['SE', 'TA', 'CA', 'MI'], ['CA', 'MI', 'SE', 'TA'], 'CA + MI + SE + TA forma CAMISETA.', { stimulus: 'CAMISETA', visual: '👕' }),
  ], 6),
  activity('words', 'palavras-significados', 'Pontes de significado', 'Ligue palavras às pistas que explicam o que elas nomeiam.', 'match', 'developing', 'Relação entre palavra e significado', 'Associar nomes a descrições, funções e opostos em vocabulário cotidiano.', 'Aceite que a criança explique primeiro com suas próprias palavras. Depois, procure a descrição equivalente.', [
    match('Ligue cada animal à pista que combina com ele.', ['ABELHA', 'ARANHA', 'PEIXE'], ['Tem oito pernas', 'Vive na água e tem nadadeiras', 'Produz mel'], ['Produz mel', 'Tem oito pernas', 'Vive na água e tem nadadeiras'], 'A abelha produz mel, a aranha tem oito pernas e o peixe vive na água e tem nadadeiras.'),
    match('Ligue cada objeto à sua função.', ['GUARDA-CHUVA', 'TESOURA', 'TRAVESSEIRO'], ['Apoiar a cabeça ao dormir', 'Proteger da chuva', 'Cortar papel'], ['Proteger da chuva', 'Cortar papel', 'Apoiar a cabeça ao dormir'], 'Usamos guarda-chuva para a chuva, tesoura para cortar papel e travesseiro para apoiar a cabeça.'),
    match('Ligue cada palavra ao seu oposto.', ['ABERTO', 'QUENTE', 'PERTO'], ['LONGE', 'FECHADO', 'FRIO'], ['FECHADO', 'FRIO', 'LONGE'], 'Os pares de opostos são ABERTO e FECHADO, QUENTE e FRIO, PERTO e LONGE.'),
    match('Ligue cada lugar ao que fazemos nele.', ['BIBLIOTECA', 'PISCINA', 'PADARIA'], ['Comprar pão', 'Ler e emprestar livros', 'Nadar'], ['Ler e emprestar livros', 'Nadar', 'Comprar pão'], 'Na biblioteca podemos ler e emprestar livros; na piscina, nadar; na padaria, comprar pão.'),
  ], 6),
  activity('words', 'palavras-cestas', 'Cestas de palavras', 'Separe todas as palavras que pertencem à categoria pedida.', 'multi', 'beginner', 'Classificação semântica de palavras', 'Ler palavras familiares e agrupá-las por significado.', 'Convide a criança a acrescentar oralmente outra palavra à categoria depois de concluir cada seleção.', [
    multi('Marque todos os nomes de frutas.', ['MANGA', 'CADEIRA', 'PERA', 'CADERNO'], ['MANGA', 'PERA'], 'MANGA e PERA são nomes de frutas. CADEIRA e CADERNO são objetos.', { visual: '🧺' }),
    multi('Marque todos os materiais usados para escrever ou desenhar.', ['LÁPIS', 'COLHER', 'GIZ', 'SAPATO'], ['LÁPIS', 'GIZ'], 'LÁPIS e GIZ podem ser usados para escrever ou desenhar.'),
    multi('Marque todos os nomes de animais.', ['COELHO', 'JANELA', 'TARTARUGA', 'TOALHA'], ['COELHO', 'TARTARUGA'], 'COELHO e TARTARUGA são animais. JANELA e TOALHA são objetos.'),
    multi('Marque todas as palavras que indicam uma ação.', ['PULAR', 'AZUL', 'CANTAR', 'MESA'], ['PULAR', 'CANTAR'], 'PULAR e CANTAR dizem o que alguém faz. AZUL indica uma cor e MESA nomeia um objeto.'),
  ], 6),
  activity('words', 'palavras-visitante', 'O visitante do baú', 'Encontre a palavra que pertence a outra categoria.', 'intruder', 'developing', 'Reconhecimento de categorias semânticas', 'Identificar a palavra que não pertence à categoria explícita do grupo.', 'Pergunte por que a palavra escolhida fica de fora. Explore o significado, sem depender apenas da leitura rápida.', [
    choice('Este baú guarda nomes de cores. Qual palavra está fora do grupo?', ['VERDE', 'AZUL', 'REDONDO', 'AMARELO'], 'REDONDO', 'REDONDO indica uma forma. VERDE, AZUL e AMARELO são cores.'),
    choice('Este baú guarda meios de transporte. Qual palavra está fora do grupo?', ['TREM', 'BARCO', 'AVIÃO', 'COLCHÃO'], 'COLCHÃO', 'COLCHÃO é usado para deitar. TREM, BARCO e AVIÃO são meios de transporte.'),
    choice('Este baú guarda partes do corpo. Qual palavra está fora do grupo?', ['JOELHO', 'COTOVELO', 'CHAPÉU', 'OMBRO'], 'CHAPÉU', 'CHAPÉU é uma peça de roupa. JOELHO, COTOVELO e OMBRO são partes do corpo.'),
    choice('Este baú guarda objetos da cozinha. Qual palavra está fora do grupo?', ['PANELA', 'GARFO', 'COPO', 'BICICLETA'], 'BICICLETA', 'BICICLETA é um meio de transporte. PANELA, GARFO e COPO são usados na cozinha.'),
  ]),
  activity('words', 'palavras-detetive', 'Detetive dos significados', 'Use a frase como pista para entender palavras e encontrar opostos.', 'choice', 'challenge', 'Vocabulário em contexto', 'Inferir significados simples a partir de uma frase e comparar palavras de sentido oposto.', 'Leia a frase inteira antes das opções. Peça à criança que troque a palavra pela resposta e veja se o sentido se mantém.', [
    choice('Na frase, o que quer dizer ENORME?', ['Muito pequeno', 'Muito grande', 'Muito frio', 'Muito rápido'], 'Muito grande', 'ENORME quer dizer muito grande. Um castelo enorme é um castelo muito grande.', { stimulus: 'A turma desenhou um castelo enorme.' }),
    choice('Qual palavra pode substituir CONTENTE sem mudar a ideia?', ['Triste', 'Molhado', 'Feliz', 'Vazio'], 'Feliz', 'CONTENTE e FELIZ têm sentidos parecidos nessa frase.', { stimulus: 'Davi ficou contente com a visita.' }),
    choice('Qual palavra indica o contrário de VAZIO?', ['Cheio', 'Macio', 'Lento', 'Baixo'], 'Cheio', 'O contrário de VAZIO é CHEIO. O cesto cheio tem coisas dentro.', { stimulus: 'O cesto está vazio.' }),
    choice('Na frase, qual sentido tem a palavra MANGA?', ['Parte de uma camisa', 'Uma fruta', 'Um brinquedo', 'Um lugar'], 'Parte de uma camisa', 'A pista é CAMISA. Aqui, MANGA é a parte da roupa que cobre o braço.', { stimulus: 'A manga da camisa ficou molhada.' }),
  ], 6),

  activity('sentences', 'frases-construtores', 'Construtores de pequenas cenas', 'Organize as palavras para contar quatro cenas do dia a dia.', 'order', 'beginner', 'Ordenação de palavras em frases', 'Construir frases com sentido, respeitando a palavra inicial e a pontuação final.', 'Leia a frase montada apontando cada palavra. Mostre os espaços que separam uma palavra da outra.', [
    order('Monte a frase começando com A.', ['canta.', 'menina', 'A'], ['A', 'menina', 'canta.'], 'A menina canta. A frase conta quem faz a ação e qual é a ação.', { visual: '🎵' }),
    order('Monte a frase começando com O.', ['corre', 'O', 'jardim.', 'no', 'cachorro'], ['O', 'cachorro', 'corre', 'no', 'jardim.'], 'O cachorro corre no jardim. A expressão NO JARDIM indica o lugar.', { visual: '🐕' }),
    order('Monte a frase começando com A.', ['um', 'cartaz.', 'A', 'fez', 'turma'], ['A', 'turma', 'fez', 'um', 'cartaz.'], 'A turma fez um cartaz. UM acompanha o nome CARTAZ.'),
    order('Monte a frase começando com Beto.', ['suco.', 'Beto', 'copo', 'bebe', 'de', 'um'], ['Beto', 'bebe', 'um', 'copo', 'de', 'suco.'], 'Beto bebe um copo de suco. Leia juntando as palavras para compreender a cena.', { visual: '🥤' }),
  ], 6),
  activity('sentences', 'frases-completar', 'A palavra que faz sentido', 'Escolha a palavra que completa a ideia de cada frase.', 'completion', 'developing', 'Coerência e concordância em frases', 'Completar frases usando pistas de significado e de concordância.', 'Converse sobre as duas pistas: o que combina com a cena e o que combina com as outras palavras da frase.', [
    choice('Qual palavra completa a frase com sentido?', ['voa', 'late', 'escreve', 'cozinha'], 'late', 'O cachorro LATE. As outras ações não descrevem o som feito por ele.', { stimulus: 'O cachorro ___ quando ouve a campainha.' }),
    choice('Qual palavra completa a frase de forma adequada?', ['brincam', 'brinca', 'brincou', 'brincando'], 'brincam', 'AS CRIANÇAS está no plural. Por isso, usamos BRINCAM.', { stimulus: 'As crianças ___ no recreio.' }),
    choice('Complete a frase usando o nome de algo que enxuga.', ['toalha', 'bola', 'nuvem', 'pedra'], 'toalha', 'A TOALHA é usada para enxugar as mãos.', { stimulus: 'Depois de lavar as mãos, uso a ___.' }),
    choice('Qual palavra mostra que a segunda ação acontece depois da primeira?', ['Depois', 'Ontem', 'Nunca', 'Debaixo'], 'Depois', 'DEPOIS indica a ação que vem em seguida.', { stimulus: 'Primeiro guardo os lápis. ___ fecho o estojo.' }),
  ]),
  activity('sentences', 'frases-conferentes', 'Conferentes das frases', 'Leia com atenção e decida se cada descoberta está correta.', 'true-false', 'developing', 'Compreensão literal e pontuação', 'Conferir informações expressas em frases e reconhecer marcas básicas de pontuação.', 'Peça que a criança aponte a palavra ou o sinal que sustenta a resposta. Nas falsas, proponha uma correção oral.', [
    choice('É verdade que a frase faz uma pergunta?', ['Verdadeiro', 'Falso'], 'Verdadeiro', 'A frase pergunta onde está o livro e termina com o sinal de interrogação.', { stimulus: 'Onde está meu livro?' }),
    choice('É verdade que foi Caio quem pintou o barco?', ['Verdadeiro', 'Falso'], 'Falso', 'A frase diz que IARA pintou o barco. Caio não aparece nessa informação.', { stimulus: 'Iara pintou o barco de azul.' }),
    choice('É verdade que as botas ficaram perto da porta?', ['Verdadeiro', 'Falso'], 'Verdadeiro', 'AO LADO DA PORTA indica que as botas estão perto dela.', { stimulus: 'As botas ficaram ao lado da porta.' }),
    choice('É verdade que a frase termina com um ponto de interrogação?', ['Verdadeiro', 'Falso'], 'Falso', 'A frase termina com !, o ponto de exclamação. O ponto de interrogação é ?.', { stimulus: 'Que surpresa boa!' }),
  ]),
  activity('sentences', 'frases-perguntas', 'Perguntas encontram respostas', 'Construa pontes entre perguntas e respostas que combinam.', 'match', 'developing', 'Relação entre perguntas e informações', 'Diferenciar perguntas sobre pessoa, lugar, tempo, objeto e motivo.', 'Retome palavras como QUEM, ONDE e QUANDO. Mostre que cada uma pede um tipo diferente de informação.', [
    match('Leia a frase e ligue cada pergunta à resposta.', ['Quem?', 'O quê?', 'Onde?'], ['Na praça', 'Nina', 'Uma pipa'], ['Nina', 'Uma pipa', 'Na praça'], 'Nina é a pessoa, uma pipa é o objeto e a praça é o lugar.', { stimulus: 'Nina empina uma pipa na praça.' }),
    match('Leia a frase e ligue cada pergunta à resposta.', ['Quem plantou?', 'O que plantou?', 'Quando plantou?'], ['Ontem', 'Uma muda', 'O avô'], ['O avô', 'Uma muda', 'Ontem'], 'O avô plantou uma muda. A palavra ONTEM informa quando isso aconteceu.', { stimulus: 'Ontem, o avô plantou uma muda.' }),
    match('Ligue cada pergunta à resposta indicada na frase.', ['Quem se abrigou?', 'Onde se abrigou?', 'Por que se abrigou?'], ['Porque chovia', 'Léo', 'Na varanda'], ['Léo', 'Na varanda', 'Porque chovia'], 'Léo é quem se abrigou; a varanda é o lugar; a chuva é o motivo.', { stimulus: 'Léo se abrigou na varanda porque chovia.' }),
    match('Ligue cada começo ao final que forma uma frase com sentido.', ['O peixe', 'A cozinheira', 'O avião'], ['prepara a sopa.', 'decola do aeroporto.', 'nada no aquário.'], ['nada no aquário.', 'prepara a sopa.', 'decola do aeroporto.'], 'O peixe nada no aquário. A cozinheira prepara a sopa. O avião decola do aeroporto.'),
  ], 6),
  activity('sentences', 'frases-varias-pistas', 'Todas as pistas da cena', 'Marque todas as informações que a frase permite confirmar.', 'multi', 'challenge', 'Localização de múltiplas informações', 'Selecionar informações explícitas sem acrescentar detalhes não presentes na frase.', 'Diferencie o que o texto diz do que apenas imaginamos. Uma opção possível na vida real pode não estar confirmada aqui.', [
    multi('Marque tudo o que a frase informa.', ['Lia levou maçãs', 'Lia levou bananas', 'Lia levou uvas', 'Lia levou peras'], ['Lia levou maçãs', 'Lia levou bananas'], 'A frase menciona maçãs e bananas. Não informa que Lia levou outras frutas.', { stimulus: 'Lia levou maçãs e bananas para o piquenique.' }),
    multi('Marque todas as informações confirmadas.', ['O gato é cinza', 'O gato está na cadeira', 'O gato está na cama', 'O gato é branco'], ['O gato é cinza', 'O gato está na cadeira'], 'O texto informa a cor CINZA e o lugar NA CADEIRA.', { stimulus: 'O gato cinza dorme na cadeira.' }),
    multi('Marque todas as frases que fazem uma pergunta.', ['Você vem brincar?', 'A bola caiu.', 'Que horas são?', 'Que festa bonita!'], ['Você vem brincar?', 'Que horas são?'], 'VOCÊ VEM BRINCAR? e QUE HORAS SÃO? pedem uma resposta e terminam com ?.'),
    multi('Marque todas as ações que Rafa realizou.', ['Lavou as mãos', 'Guardou o brinquedo', 'Pintou o muro', 'Tocou violão'], ['Lavou as mãos', 'Guardou o brinquedo'], 'A frase conta duas ações: guardar o brinquedo e lavar as mãos.', { stimulus: 'Rafa guardou o brinquedo e lavou as mãos.' }),
  ], 6),
  activity('sentences', 'frases-observatorio', 'Observatório das pequenas pistas', 'Descubra quem, onde e por que as ações aconteceram.', 'choice', 'challenge', 'Interpretação de relações em frases', 'Compreender negação, causa, comparação e referências em frases curtas.', 'Leia cada frase duas vezes se preciso. Destaque a palavra que muda o sentido, como NÃO ou PORQUE.', [
    choice('Qual objeto Dani NÃO levou?', ['A garrafa', 'O casaco', 'A lancheira', 'O livro'], 'O casaco', 'A palavra NÃO indica que Dani não levou o casaco. A frase não informa onde o casaco ficou.', { stimulus: 'Dani levou a garrafa, mas não levou o casaco.' }),
    choice('Por que a turma entrou na sala?', ['Porque escureceu', 'Porque começou a chover', 'Porque o ônibus chegou', 'Porque terminou o livro'], 'Porque começou a chover', 'A expressão PORQUE COMEÇOU A CHOVER explica o motivo.', { stimulus: 'A turma entrou na sala porque começou a chover.' }),
    choice('Quem é mais alto nessa comparação?', ['Ivo', 'Bia', 'Os dois têm a mesma altura', 'A frase não compara alturas'], 'Bia', 'Se Bia é mais alta que Ivo, Bia tem a maior altura entre os dois.', { stimulus: 'Bia é mais alta que Ivo.' }),
    choice('Na segunda frase, ELA se refere a quem?', ['À semente', 'À janela', 'À planta', 'À chuva'], 'À planta', 'ELA retoma A PLANTA. É a planta que cresceu perto da janela.', { stimulus: 'A planta recebeu água. Ela cresceu perto da janela.' }),
  ], 6),

  activity('reading', 'leitura-biblioteca', 'Uma descoberta na biblioteca', 'Leia uma história curta e encontre as pistas sobre os personagens.', 'reading', 'beginner', 'Localização de informações em narrativa', 'Identificar personagem, lugar, objeto e ação final em um pequeno texto.', 'Leia o texto compartilhando a atenção com a criança. Volte à frase que responde à pergunta sempre que necessário.', [
    choice('Quem encontrou o livro?', ['A professora', 'Téo', 'Bia', 'O bibliotecário'], 'Bia', 'O texto começa contando que Bia encontrou o livro.', { stimulus: 'Na biblioteca da escola, Bia encontrou um livro sobre tartarugas. Ela chamou Téo para olhar as figuras. Os dois leram juntos e devolveram o livro à estante.' }),
    choice('Onde a história aconteceu?', ['Na praia', 'Na biblioteca da escola', 'No mercado', 'Na piscina'], 'Na biblioteca da escola', 'O lugar aparece logo no início: NA BIBLIOTECA DA ESCOLA.', { stimulus: 'Na biblioteca da escola, Bia encontrou um livro sobre tartarugas. Ela chamou Téo para olhar as figuras. Os dois leram juntos e devolveram o livro à estante.' }),
    choice('Sobre qual animal era o livro?', ['Golfinhos', 'Borboletas', 'Tartarugas', 'Tucanos'], 'Tartarugas', 'Bia encontrou um livro SOBRE TARTARUGAS.', { stimulus: 'Na biblioteca da escola, Bia encontrou um livro sobre tartarugas. Ela chamou Téo para olhar as figuras. Os dois leram juntos e devolveram o livro à estante.', visual: '📚' }),
    choice('O que fizeram com o livro no final?', ['Levaram para a praia', 'Devolveram à estante', 'Colocaram no jardim', 'Esconderam na mochila'], 'Devolveram à estante', 'A última parte do texto conta que os dois devolveram o livro à estante.', { stimulus: 'Na biblioteca da escola, Bia encontrou um livro sobre tartarugas. Ela chamou Téo para olhar as figuras. Os dois leram juntos e devolveram o livro à estante.' }),
  ], 6),
  activity('reading', 'leitura-bilhete', 'Uma mensagem para a turma', 'Investigue para quem é o bilhete e o que ele está combinando.', 'reading', 'developing', 'Compreensão de bilhete e finalidade do texto', 'Identificar destinatário, autoria, pedido e momento em um bilhete.', 'Antes das perguntas, converse sobre a função de um bilhete. A assinatura indica quem escreveu a mensagem.', [
    choice('Para quem o bilhete foi escrito?', ['Para a turma', 'Para o motorista', 'Para a cozinheira', 'Para os vizinhos'], 'Para a turma', 'A palavra TURMA no início mostra para quem a mensagem foi escrita.', { stimulus: 'Turma, amanhã vamos cuidar da horta depois do recreio. Tragam um boné. Os regadores já estão na escola. Até amanhã! Professora Rosa' }),
    choice('O que os estudantes devem levar?', ['Um regador', 'Um boné', 'Uma bicicleta', 'Um violão'], 'Um boné', 'O pedido é TRAGAM UM BONÉ. Os regadores já estão na escola.', { stimulus: 'Turma, amanhã vamos cuidar da horta depois do recreio. Tragam um boné. Os regadores já estão na escola. Até amanhã! Professora Rosa' }),
    choice('Quando a turma vai cuidar da horta?', ['Hoje, antes do recreio', 'Amanhã, depois do recreio', 'Hoje, durante a noite', 'Amanhã, antes da aula'], 'Amanhã, depois do recreio', 'O bilhete informa o dia, AMANHÃ, e o momento, DEPOIS DO RECREIO.', { stimulus: 'Turma, amanhã vamos cuidar da horta depois do recreio. Tragam um boné. Os regadores já estão na escola. Até amanhã! Professora Rosa' }),
    choice('Quem escreveu o bilhete?', ['A turma inteira', 'A professora Rosa', 'O jardineiro', 'A diretora Ana'], 'A professora Rosa', 'A assinatura PROFESSORA ROSA mostra quem escreveu a mensagem.', { stimulus: 'Turma, amanhã vamos cuidar da horta depois do recreio. Tragam um boné. Os regadores já estão na escola. Até amanhã! Professora Rosa' }),
  ], 6),
  activity('reading', 'leitura-piquenique', 'Conferindo o piquenique', 'Compare as afirmações com as informações de uma pequena história.', 'true-false', 'beginner', 'Verificação de informações explícitas', 'Confirmar ou rejeitar afirmações recuperando evidências do texto.', 'Nas respostas falsas, peça a informação correta. Releia o trecho em vez de pedir que a criança memorize tudo.', [
    choice('É verdade que o piquenique aconteceu no domingo?', ['Verdadeiro', 'Falso'], 'Falso', 'O texto informa que o piquenique aconteceu no SÁBADO.', { stimulus: 'No sábado, Nara e seu pai fizeram um piquenique no parque. Levaram apenas pão, queijo e água. Quando começou a chover, guardaram tudo e voltaram para casa.' }),
    choice('É verdade que Nara foi ao parque com seu pai?', ['Verdadeiro', 'Falso'], 'Verdadeiro', 'O texto diz NARA E SEU PAI e informa que o piquenique foi NO PARQUE.', { stimulus: 'No sábado, Nara e seu pai fizeram um piquenique no parque. Levaram apenas pão, queijo e água. Quando começou a chover, guardaram tudo e voltaram para casa.' }),
    choice('É verdade que eles levaram suco de uva?', ['Verdadeiro', 'Falso'], 'Falso', 'O texto menciona ÁGUA, pão e queijo. Não diz que eles levaram suco de uva.', { stimulus: 'No sábado, Nara e seu pai fizeram um piquenique no parque. Levaram apenas pão, queijo e água. Quando começou a chover, guardaram tudo e voltaram para casa.' }),
    choice('É verdade que eles voltaram para casa quando começou a chover?', ['Verdadeiro', 'Falso'], 'Verdadeiro', 'A chuva fez os dois guardarem tudo e voltarem para casa.', { stimulus: 'No sábado, Nara e seu pai fizeram um piquenique no parque. Levaram apenas pão, queijo e água. Quando começou a chover, guardaram tudo e voltaram para casa.', visual: '🧺' }),
  ], 6),
  activity('reading', 'leitura-varias-descobertas', 'Várias descobertas em um texto', 'Escolha todas as informações que cada texto apresenta.', 'multi', 'developing', 'Compreensão de textos informativos e instruções', 'Localizar duas ou mais informações explícitas em textos de diferentes finalidades.', 'Reforce que todas as opções marcadas precisam de uma pista no texto. Conhecimento de mundo ajuda, mas não substitui a leitura.', [
    multi('Segundo o texto, o que devemos fazer com um livro emprestado?', ['Cuidar das páginas', 'Devolver no dia combinado', 'Rasgar a capa', 'Escrever em todas as folhas'], ['Cuidar das páginas', 'Devolver no dia combinado'], 'O texto pede cuidado com as páginas e devolução no dia combinado.', { stimulus: 'Ao pegar um livro emprestado, cuide das páginas. Depois da leitura, devolva-o no dia combinado para que outra pessoa também possa ler.' }),
    multi('Quais materiais a instrução pede?', ['Papel', 'Lápis de cor', 'Farinha', 'Sal'], ['Papel', 'Lápis de cor'], 'Para desenhar o cartão, a instrução pede PAPEL e LÁPIS DE COR.', { stimulus: 'Para fazer o cartão, separe papel e lápis de cor. Dobre o papel ao meio e faça um desenho na parte da frente.' }),
    multi('Quais animais foram vistos pela turma?', ['Formigas', 'Borboletas', 'Baleias', 'Pinguins'], ['Formigas', 'Borboletas'], 'A turma viu formigas perto do tronco e borboletas nas flores.', { stimulus: 'No jardim, a turma observou formigas perto de um tronco. Sobre as flores, duas borboletas voavam. Todos registraram as descobertas no caderno.' }),
    multi('Quais atitudes a placa pede aos visitantes?', ['Andar pelas trilhas', 'Levar o lixo embora', 'Arrancar as flores', 'Alimentar todos os animais'], ['Andar pelas trilhas', 'Levar o lixo embora'], 'Os dois pedidos da placa são andar pelas trilhas e levar o lixo embora.', { stimulus: 'BEM-VINDOS AO PARQUE! Andem pelas trilhas e levem seu lixo embora. Assim, todos ajudam a cuidar deste lugar.' }),
  ], 7),
  activity('reading', 'leitura-conexoes', 'Conexões de leitor', 'Relacione informações em cartazes, listas, agendas e diálogos.', 'match', 'developing', 'Relação de informações em textos cotidianos', 'Associar pessoas, dias, espaços e falas às informações correspondentes no texto.', 'Explore como cada texto organiza a informação. Volte ao trecho de um par por vez para reduzir a carga de memória.', [
    match('Ligue cada oficina ao espaço indicado no cartaz.', ['Pintura', 'Música', 'Leitura'], ['Biblioteca', 'Sala azul', 'Pátio'], ['Sala azul', 'Pátio', 'Biblioteca'], 'O cartaz indica pintura na sala azul, música no pátio e leitura na biblioteca.', { stimulus: 'FESTA DAS OFICINAS — Pintura: sala azul. Música: pátio. Leitura: biblioteca.' }),
    match('Ligue cada criança ao que vai levar.', ['Lia', 'Rui', 'Eva'], ['Copos', 'Frutas', 'Toalha'], ['Frutas', 'Toalha', 'Copos'], 'A lista combina frutas com Lia, toalha com Rui e copos com Eva.', { stimulus: 'Lista do lanche coletivo: Lia leva frutas. Rui leva a toalha. Eva leva os copos.' }),
    match('Ligue cada dia à atividade da agenda.', ['Segunda-feira', 'Quarta-feira', 'Sexta-feira'], ['Teatro', 'Horta', 'Biblioteca'], ['Horta', 'Biblioteca', 'Teatro'], 'A agenda reserva segunda para a horta, quarta para a biblioteca e sexta para o teatro.', { stimulus: 'AGENDA DA TURMA — Segunda-feira: cuidar da horta. Quarta-feira: visitar a biblioteca. Sexta-feira: ensaiar o teatro.' }),
    match('Ligue cada personagem ao que escolheu desenhar.', ['Ana', 'Breno', 'Cris'], ['Um barco', 'Uma árvore', 'Uma estrela'], ['Uma árvore', 'Uma estrela', 'Um barco'], 'Ana escolheu uma árvore, Breno uma estrela e Cris um barco.', { stimulus: 'Ana disse: Vou desenhar uma árvore. Breno respondeu: Eu escolho uma estrela. Cris completou: Meu desenho será um barco.' }),
  ], 7),
  activity('reading', 'leitura-entrelinhas', 'Pistas entre as linhas', 'Junte pistas para entender motivos, sentimentos e o assunto principal.', 'reading', 'challenge', 'Inferência apoiada em evidências do texto', 'Inferir informações simples e reconhecer a ideia principal usando pistas explícitas.', 'Pergunte quais palavras ajudaram na conclusão. Apresente a inferência como uma leitura das pistas, e não como adivinhação.', [
    choice('Por que Malu pegou o guarda-chuva?', ['Porque esperava chuva', 'Porque queria pintar', 'Porque estava com fome', 'Porque precisava escrever'], 'Porque esperava chuva', 'O céu escuro e o trovão são pistas de chuva. Por isso, pegar o guarda-chuva faz sentido.', { stimulus: 'Malu olhou pela janela. O céu estava escuro e um trovão soou. Antes de sair, ela pegou o guarda-chuva.' }),
    choice('Como Ivo provavelmente se sentiu ao receber a carta?', ['Feliz', 'Zangado', 'Assustado', 'Com frio'], 'Feliz', 'O sorriso e a vontade de guardar a carta com carinho são pistas de alegria.', { stimulus: 'Ivo abriu a carta da amiga e deu um grande sorriso. Leu a mensagem duas vezes e a guardou com carinho.' }),
    choice('Qual título combina melhor com o texto inteiro?', ['Uma ideia para compartilhar', 'O barco perdido', 'Uma corrida na chuva', 'O jantar do dragão'], 'Uma ideia para compartilhar', 'O texto conta como duas crianças encontraram uma maneira de usar juntas o único lápis verde.', { stimulus: 'Só havia um lápis verde na mesa. Joana queria desenhar uma folha, e Sami, uma árvore. Eles combinaram de usar o lápis um de cada vez. Assim, os dois terminaram seus desenhos.' }),
    choice('No poema, por que o passarinho canta baixinho?', ['Para não acordar o ninho', 'Porque procura um sapato', 'Para chamar um barco', 'Porque perdeu um livro'], 'Para não acordar o ninho', 'A última parte do poema explica o motivo de cantar baixinho: não acordar o ninho.', { stimulus: 'No galho bem pertinho, / canta um passarinho. / Sua voz vai de mansinho, / para não acordar o ninho.', visual: '🐦' }),
  ], 8),

  activity('logic', 'logica-padroes', 'Jardim dos padrões', 'Descubra a regra que se repete e complete a sequência.', 'logic', 'beginner', 'Reconhecimento de padrões repetitivos', 'Identificar o bloco de repetição de sequências de formas, cores e movimentos.', 'Peça que a criança fale o bloco que se repete antes de escolher. Use tampinhas ou gestos para reproduzir a sequência.', [
    choice('A regra é repetir SOL, LUA. O que vem agora?', ['SOL', 'LUA', 'NUVEM', 'ESTRELA'], 'SOL', 'O bloco é SOL, LUA. Depois da LUA, começa outro bloco com SOL.', { stimulus: 'SOL → LUA → SOL → LUA → ?' }),
    choice('A regra é repetir PALMA, PALMA, PULO. O que vem agora?', ['PULO', 'PALMA', 'GIRO', 'PAUSA'], 'PULO', 'Cada bloco tem duas palmas e um pulo. Depois das duas palmas, vem PULO.', { stimulus: 'PALMA → PALMA → PULO → PALMA → PALMA → ?' }),
    choice('A regra é repetir VERMELHO, AZUL, VERDE. O que vem agora?', ['AZUL', 'VERMELHO', 'VERDE', 'AMARELO'], 'VERDE', 'O bloco termina com VERDE. Ele vem depois de VERMELHO e AZUL.', { stimulus: 'VERMELHO → AZUL → VERDE → VERMELHO → AZUL → ?' }),
    choice('A regra é acrescentar duas estrelas em cada grupo. Quantas vêm agora?', ['5', '6', '7', '8'], '8', 'Começamos com 2 e acrescentamos 2: 2, 4, 6, 8.', { stimulus: '2 estrelas → 4 estrelas → 6 estrelas → ?', visual: '⭐' }),
  ]),
  activity('logic', 'logica-receitas', 'Receitas para um pequeno robô', 'Organize instruções para que cada tarefa funcione.', 'order', 'developing', 'Construção de sequências de instruções', 'Ordenar passos de um procedimento respeitando as dependências entre ações.', 'Antes de tocar na tela, encene os passos. Pergunte o que precisa acontecer primeiro para o próximo passo ser possível.', [
    order('Organize este plantio, começando por abrir o buraco e terminando por regar a terra.', ['Cobrir a semente com terra', 'Regar a terra', 'Abrir um pequeno buraco', 'Colocar a semente no buraco'], ['Abrir um pequeno buraco', 'Colocar a semente no buraco', 'Cobrir a semente com terra', 'Regar a terra'], 'Primeiro abrimos o buraco, colocamos a semente e a cobrimos. Depois regamos a terra.', { visual: '🌱' }),
    order('Organize os passos para entregar uma carta dentro de um envelope fechado.', ['Fechar o envelope', 'Entregar o envelope', 'Escrever a carta', 'Colocar a carta no envelope'], ['Escrever a carta', 'Colocar a carta no envelope', 'Fechar o envelope', 'Entregar o envelope'], 'Escrevemos antes de guardar a carta. Só fechamos o envelope depois de colocar a carta dentro.'),
    order('O robô deve seguir esta rota. Organize as paradas, começando na BASE.', ['FAROL', 'BOSQUE', 'BASE', 'PONTE'], ['BASE', 'PONTE', 'BOSQUE', 'FAROL'], 'O roteiro indica BASE, depois PONTE, BOSQUE e, por último, FAROL.', { stimulus: 'Rota: BASE → PONTE → BOSQUE → FAROL' }),
    order('Organize este programa de desenho: primeiro desenhe, depois pinte, recorte e cole.', ['Recortar o desenho', 'Colar no cartaz', 'Desenhar no papel', 'Pintar o desenho'], ['Desenhar no papel', 'Pintar o desenho', 'Recortar o desenho', 'Colar no cartaz'], 'O programa pede quatro passos nesta ordem: desenhar, pintar, recortar e colar.'),
  ], 7),
  activity('logic', 'logica-filtros', 'Portais das regras', 'Deixe passar todas as opções que atendem à regra do portal.', 'multi', 'developing', 'Classificação por condições e atributos', 'Aplicar regras com uma ou duas condições e selecionar todos os casos válidos.', 'Leia a regra em voz alta a cada rodada. Nas duas condições, verifique uma de cada vez antes de liberar o item.', [
    multi('O portal aceita apenas animais. Marque todos os que podem passar.', ['TUCANO', 'PEDRA', 'JACARÉ', 'CADEIRA'], ['TUCANO', 'JACARÉ'], 'TUCANO e JACARÉ são animais. PEDRA e CADEIRA não atendem à regra.', { visual: '🚪' }),
    multi('A regra pede botões AZUIS e REDONDOS. Marque todos os que servem.', ['Azul, redondo e pequeno', 'Azul, quadrado e pequeno', 'Azul, redondo e grande', 'Vermelho, redondo e grande'], ['Azul, redondo e pequeno', 'Azul, redondo e grande'], 'Os dois botões azuis e redondos atendem às duas condições. O tamanho não faz parte da regra.'),
    multi('A regra pede números maiores que 3 e menores que 7. Marque todos os que servem.', ['2', '4', '6', '8'], ['4', '6'], '4 e 6 são maiores que 3 e menores que 7. 2 é pequeno demais e 8 é grande demais.'),
    multi('Para organizar os livros por cor, quais passos ajudam a cumprir a tarefa?', ['Separar os livros pela cor da capa', 'Juntar os livros da mesma cor', 'Misturar tudo de novo', 'Esconder os livros debaixo da mesa'], ['Separar os livros pela cor da capa', 'Juntar os livros da mesma cor'], 'Separar pela cor e juntar cores iguais são partes da tarefa de organizar. Misturar ou esconder não cumpre o objetivo.'),
  ], 7),
  activity('logic', 'logica-comandos', 'Ligue o comando à ação', 'Relacione símbolos, tarefas e pistas para dar instruções claras.', 'match', 'developing', 'Representação de comandos e decomposição', 'Associar instruções a ações e dividir uma tarefa em partes com funções distintas.', 'Explique que um símbolo só funciona como comando quando todos combinam seu significado. Teste os pares com movimentos.', [
    match('Neste jogo, ligue cada seta ao movimento que ela representa.', ['↑', '→', '↓'], ['Ir para baixo', 'Ir para cima', 'Ir para a direita'], ['Ir para cima', 'Ir para a direita', 'Ir para baixo'], 'A seta ↑ aponta para cima, → para a direita e ↓ para baixo.'),
    match('Ligue cada comando à ação combinada.', ['INICIAR', 'REPETIR', 'PARAR'], ['Fazer a ação outra vez', 'Encerrar o movimento', 'Começar o movimento'], ['Começar o movimento', 'Fazer a ação outra vez', 'Encerrar o movimento'], 'INICIAR começa, REPETIR faz de novo e PARAR encerra o movimento.'),
    match('A tarefa é preparar um cartaz. Ligue cada parte à sua função.', ['Escrever o título', 'Fazer a ilustração', 'Fixar na parede'], ['Mostrar o cartaz para a turma', 'Dar um nome ao cartaz', 'Representar a ideia com um desenho'], ['Dar um nome ao cartaz', 'Representar a ideia com um desenho', 'Mostrar o cartaz para a turma'], 'Título, ilustração e exposição são partes diferentes da tarefa de preparar o cartaz.'),
    match('Ligue cada problema ao ajuste que resolve a situação descrita.', ['A trilha está escura', 'A planta está com a terra seca', 'O desenho ficou sem cor'], ['Colorir o desenho', 'Acender a lanterna', 'Regar a terra'], ['Acender a lanterna', 'Regar a terra', 'Colorir o desenho'], 'A lanterna ilumina a trilha, a água umedece a terra e a pintura dá cor ao desenho.'),
  ], 7),
  activity('logic', 'logica-depuracao', 'Oficina dos pequenos erros', 'Encontre o erro no plano e escolha um ajuste que faça a tarefa funcionar.', 'logic', 'challenge', 'Identificação e correção de erros em sequências', 'Comparar um resultado com o objetivo e corrigir uma instrução ou regra.', 'Chame o erro de pista para melhorar o plano. Simule o programa antes e depois da correção para comparar os resultados.', [
    choice('O robô começa na casa 1. Cada DIREITA avança uma casa. O plano tem duas DIREITAS. Como fazê-lo chegar à casa 4?', ['Adicionar uma DIREITA', 'Retirar uma DIREITA', 'Adicionar uma ESQUERDA', 'Parar na casa 1'], 'Adicionar uma DIREITA', 'Duas DIREITAS levam da casa 1 à 3. Mais uma DIREITA leva à casa 4.', { stimulus: 'Trilha: 1 → 2 → 3 → 4' }),
    choice('O envelope precisa sair fechado e com a carta dentro. Qual ajuste corrige o plano?', ['Colocar a carta antes de fechar', 'Fechar o envelope duas vezes', 'Entregar antes de escrever', 'Pular a escrita da carta'], 'Colocar a carta antes de fechar', 'Não podemos colocar a carta em um envelope já fechado. É preciso guardar a carta e só depois fechar.', { stimulus: 'Plano com erro: escrever a carta → fechar o envelope → colocar a carta dentro → entregar.' }),
    choice('A máquina deve carimbar uma estrela em cada um dos três cartões. Ela repetiu o carimbo só duas vezes. O que falta?', ['Mais um carimbo no cartão vazio', 'Apagar os dois carimbos', 'Pintar a mesa', 'Guardar todos os cartões vazios'], 'Mais um carimbo no cartão vazio', 'Há três cartões e só dois receberam estrelas. Falta carimbar o terceiro.', { stimulus: 'Cartão 1: estrela. Cartão 2: estrela. Cartão 3: vazio.' }),
    choice('A regra é repetir A, B. Qual letra precisa mudar para consertar a sequência?', ['A última letra, de A para B', 'A primeira letra, de A para B', 'A segunda letra, de B para A', 'Nenhuma letra'], 'A última letra, de A para B', 'Os pares devem ser A-B, A-B, A-B. A última letra precisa ser B.', { stimulus: 'A → B → A → B → A → A' }),
  ], 8),
  activity('logic', 'logica-decisoes', 'Decisões na ilha dos robôs', 'Use condições e repetições para prever o próximo passo.', 'logic', 'challenge', 'Condições, repetições e previsão de resultados', 'Executar mentalmente instruções simples com SE, SENÃO e REPETIR.', 'Separe o que é condição do que é ação. Use objetos para repetir o comando e registrar o resultado a cada rodada.', [
    choice('A regra é: SE chover, ir ao abrigo; SENÃO, ir ao jardim. Começou a chover. Para onde o robô vai?', ['Ao abrigo', 'Ao jardim', 'Ao mercado', 'Ao lago'], 'Ao abrigo', 'A condição CHOVER aconteceu. Por isso, o robô segue a instrução IR AO ABRIGO.', { visual: '🤖' }),
    choice('A regra é: SE a caixa estiver vazia, colocar uma bola; SENÃO, fechar a tampa. A caixa já tem uma bola. O que o robô faz?', ['Coloca outra bola', 'Fecha a tampa', 'Tira a bola', 'Abre outra caixa'], 'Fecha a tampa', 'A caixa não está vazia. O robô usa o SENÃO e fecha a tampa.'),
    choice('O comando é repetir três vezes: desenhar um círculo e um quadrado. Quantas formas serão desenhadas ao todo?', ['3', '4', '6', '8'], '6', 'Cada repetição desenha duas formas. Três repetições fazem 2 + 2 + 2 = 6 formas.', { stimulus: 'REPETIR 3 VEZES: CÍRCULO → QUADRADO' }),
    choice('O robô está na casa 2. Ele anda uma casa para a direita duas vezes e depois uma para a esquerda. Onde termina?', ['Casa 1', 'Casa 2', 'Casa 3', 'Casa 4'], 'Casa 3', 'O caminho é 2 → 3 → 4 → 3. O último passo volta uma casa para a esquerda.', { stimulus: 'Casas da trilha, da esquerda para a direita: 1, 2, 3, 4, 5.' }),
  ], 8),
];
