import { sqliteTable, text, integer, uniqueIndex, index } from "drizzle-orm/sqlite-core";

export const institutions = sqliteTable("institutions", { id: text("id").primaryKey(), name: text("name").notNull(), isDemo: integer("is_demo").notNull().default(0), createdAt: text("created_at").notNull() });
export const users = sqliteTable("users", { id: text("id").primaryKey(), institutionId: text("institution_id").notNull().references(() => institutions.id, { onDelete: "cascade" }), name: text("name").notNull(), email: text("email").unique(), passwordHash: text("password_hash"), role: text("role").notNull(), studentId: text("student_id"), createdAt: text("created_at").notNull() });
export const sessions = sqliteTable("sessions", { tokenHash: text("token_hash").primaryKey(), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), role: text("role").notNull(), expiresAt: text("expires_at").notNull(), settings: text("settings").notNull().default('{}') });
export const classrooms = sqliteTable("classrooms", { id: text("id").primaryKey(), institutionId: text("institution_id").notNull().references(() => institutions.id, { onDelete: "cascade" }), name: text("name").notNull(), grade: text("grade").notNull(), teacherName: text("teacher_name").notNull(), teacherUserId: text("teacher_user_id").references(() => users.id, { onDelete: "set null" }), createdAt: text("created_at").notNull() });
export const students = sqliteTable("students", { id: text("id").primaryKey(), institutionId: text("institution_id").notNull().references(() => institutions.id, { onDelete: "cascade" }), classroomId: text("classroom_id").references(() => classrooms.id, { onDelete: "set null" }), name: text("name").notNull(), avatar: text("avatar").notNull().default('🦊'), grade: text("grade").notNull(), codeHash: text("code_hash").unique(), consentAudio: integer("consent_audio").notNull().default(0), createdAt: text("created_at").notNull() });
export const activities = sqliteTable("activities", { id: text("id").primaryKey(), institutionId: text("institution_id").notNull().references(() => institutions.id, { onDelete: "cascade" }), title: text("title").notNull(), body: text("body").notNull(), status: text("status").notNull().default('draft'), version: integer("version").notNull().default(1), createdAt: text("created_at").notNull() });
export const activityVersions = sqliteTable("activity_versions", { id: text("id").primaryKey(), activityId: text("activity_id").notNull().references(() => activities.id, { onDelete: "cascade" }), version: integer("version").notNull(), body: text("body").notNull(), createdAt: text("created_at").notNull() }, (t) => [uniqueIndex("activity_version_unique").on(t.activityId, t.version)]);
export const submissions = sqliteTable("submissions", { id: text("id").primaryKey(), institutionId: text("institution_id").notNull().references(() => institutions.id, { onDelete: "cascade" }), studentId: text("student_id").notNull().references(() => students.id, { onDelete: "cascade" }), activityId: text("activity_id").notNull(), activityVersion: integer("activity_version").notNull(), score: integer("score").notNull(), correct: integer("correct").notNull(), total: integer("total").notNull(), xpEarned: integer("xp_earned").notNull().default(0), answers: text("answers").notNull(), fingerprint: text("fingerprint").notNull(), completedAt: text("completed_at").notNull(), durationSeconds: integer("duration_seconds").notNull(), isDiagnostic: integer("is_diagnostic").notNull().default(0) }, (t) => [index("submissions_student_time").on(t.studentId, t.completedAt)]);
export const xpAwards = sqliteTable("xp_awards", { id: text("id").primaryKey(), studentId: text("student_id").notNull().references(() => students.id, { onDelete: "cascade" }), activityId: text("activity_id").notNull(), submissionId: text("submission_id").notNull().references(() => submissions.id, { onDelete: "cascade" }), xp: integer("xp").notNull() }, (t) => [uniqueIndex("xp_once_per_activity").on(t.studentId, t.activityId)]);
export const assignments = sqliteTable("assignments", { id: text("id").primaryKey(), institutionId: text("institution_id").notNull().references(() => institutions.id, { onDelete: "cascade" }), classroomId: text("classroom_id").notNull().references(() => classrooms.id, { onDelete: "cascade" }), activityId: text("activity_id").notNull(), title: text("title").notNull(), dueDate: text("due_date").notNull(), createdAt: text("created_at").notNull() });
export const notes = sqliteTable("notes", { id: text("id").primaryKey(), institutionId: text("institution_id").notNull().references(() => institutions.id, { onDelete: "cascade" }), studentId: text("student_id").notNull().references(() => students.id, { onDelete: "cascade" }), text: text("text").notNull(), type: text("type").notNull(), author: text("author").notNull(), createdAt: text("created_at").notNull() });
export const notifications = sqliteTable("notifications", { id: text("id").primaryKey(), institutionId: text("institution_id").notNull().references(() => institutions.id, { onDelete: "cascade" }), studentId: text("student_id"), title: text("title").notNull(), text: text("text").notNull(), read: integer("read").notNull().default(0), createdAt: text("created_at").notNull() });
export const recordings = sqliteTable("recordings", { id: text("id").primaryKey(), institutionId: text("institution_id").notNull().references(() => institutions.id, { onDelete: "cascade" }), studentId: text("student_id").notNull().references(() => students.id, { onDelete: "cascade" }), activityId: text("activity_id").notNull(), objectKey: text("object_key").notNull(), mimeType: text("mime_type").notNull(), size: integer("size").notNull(), createdAt: text("created_at").notNull() });
export const auditLogs = sqliteTable("audit_logs", { id: text("id").primaryKey(), institutionId: text("institution_id").notNull().references(() => institutions.id, { onDelete: "cascade" }), userId: text("user_id").notNull(), action: text("action").notNull(), detail: text("detail").notNull(), createdAt: text("created_at").notNull() });
export const rateLimits = sqliteTable("rate_limits", { key: text("key").primaryKey(), count: integer("count").notNull(), resetAt: integer("reset_at").notNull() });
