'use client';
import {useEffect,useRef,useState} from 'react';
import {Mic,Square,Upload,CheckCircle2} from 'lucide-react';
export default function Recorder({studentId,activityId,consent,onSaved}:{studentId:string;activityId:string;consent:boolean;onSaved:()=>void}){
 const [recording,setRecording]=useState(false),[url,setUrl]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false),[seconds,setSeconds]=useState(0);
 const media=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),blob=useRef<Blob|null>(null),timer=useRef<ReturnType<typeof setInterval>|null>(null),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;if(media.current?.state==='recording')media.current.stop();stream.current?.getTracks().forEach(t=>t.stop());if(timer.current)clearInterval(timer.current);};},[]);
 useEffect(()=>()=>{if(url)URL.revokeObjectURL(url);},[url]);
 const stop=()=>{if(media.current?.state==='recording')media.current.stop();stream.current?.getTracks().forEach(t=>t.stop());if(timer.current)clearInterval(timer.current);setRecording(false);};
 async function start(){try{setError('');if(!navigator.mediaDevices||!window.MediaRecorder)throw new Error('Este navegador não oferece gravação. Você pode ler em voz alta com um adulto.');const input=await navigator.mediaDevices.getUserMedia({audio:true});if(!mounted.current){input.getTracks().forEach(t=>t.stop());return;}stream.current=input;const preferred=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(t=>MediaRecorder.isTypeSupported(t));const r=new MediaRecorder(stream.current,preferred?{mimeType:preferred}:undefined);media.current=r;const chunks:BlobPart[]=[];r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};r.onstop=()=>{blob.current=new Blob(chunks,{type:r.mimeType});if(mounted.current){setUrl(URL.createObjectURL(blob.current));setRecording(false);}stream.current?.getTracks().forEach(t=>t.stop());};blob.current=null;setUrl('');r.start();setRecording(true);setSaved(false);setSeconds(0);timer.current=setInterval(()=>setSeconds(n=>{if(n>=119){if(r.state==='recording')r.stop();stream.current?.getTracks().forEach(t=>t.stop());if(timer.current)clearInterval(timer.current);}return n+1;}),1000);}catch(e){stream.current?.getTracks().forEach(t=>t.stop());if(timer.current)clearInterval(timer.current);setError(e instanceof Error?e.message:'Não foi possível acessar o microfone.');}}
 async function save(){if(!blob.current||recording||saving||!consent)return;setSaving(true);setError('');try{const form=new FormData();form.append('file',blob.current,'leitura.webm');form.append('studentId',studentId);form.append('activityId',activityId);const r=await fetch('/api/audio',{method:'POST',body:form});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error||'Não foi possível enviar a gravação.');setSaved(true);onSaved();}catch(e){setError(e instanceof Error?e.message:'Falha no envio.');}finally{setSaving(false);}}
 return <div className="recording-panel"><div><Mic size={20}/><strong>Minha leitura em voz alta</strong></div><p>Leia no seu ritmo. Sua gravação poderá ser ouvida pelo professor.</p>{!consent?<p className="muted">Um responsável precisa autorizar o uso da voz na área Família antes de gravar.</p>:<><button className={`btn ${recording?'btn-danger':'btn-secondary'}`} onClick={recording?stop:start} disabled={saving}>{recording?<Square size={16}/>:<Mic size={16}/>} {recording?`Finalizar · ${seconds}s`:url?'Gravar novamente':'Gravar minha leitura'}</button>{url&&<div className="recording-result"><audio controls src={url} aria-label="Ouvir minha gravação"/><button className="btn btn-primary" onClick={save} disabled={saving||saved}>{saved?<CheckCircle2 size={16}/>:<Upload size={16}/>} {saved?'Enviada ao professor':saving?'Enviando…':'Salvar leitura'}</button></div>}</>}{error&&<p role="alert" className="form-error">{error}</p>}</div>;
}
